# fly.toml app configuration file generated for rugstore on 2023-09-05T21:18:18+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rugstore"
primary_region = "otp"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51NLteWE9jHxnSQPXEvcC3QIEDaMBgtPGogpQcaf32iDIULSsvUPBadBERJ0xBDf4ongYz05UlF8CSjzMXYWxzc8M00hMQYxIWl"

[build]
  image = "hafthor98/rugstore:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
